sequenceDiagram
    participant A
    participant B
    A->B: solid no head
    A-->B: dashed no head
    A->>B: solid filled head
    A-->>B: dashed filled head
    A-xB: solid cross
    A--xB: dashed cross
    A-)B: solid open async
    A--)B: dashed open async
