classDiagram
    namespace Vehicles {
        class Car {
            +start() void
        }
        class Bike
    }
    namespace People {
        class Driver
        class Passenger
    }
    Driver --> Car : drives
    Passenger --> Car : rides
