mindmap
  Root
    Quadratic formula
      $$\frac{-b \pm \sqrt{b \times b - 4ac}}{2a}$$
    Area of circle
      $$\pi r \times r$$
    Imaginary unit
      $$\sqrt{-1}$$
    Greek letters
      $$\alpha \beta \gamma \delta$$
    Fractions
      $$\frac{1}{2} + \frac{1}{3} = \frac{5}{6}$$
