// Package dummy inserts waypoint nodes into the work graph for
// every edge spanning more than one rank. This is the dagre-style
// "normalize" phase, run between rank and order: ordering and
// positioning treat each chain of rank-adjacent edges as real, and
// the resulting coordinates serve as polyline waypoints so long-span
// edges no longer cut straight through unrelated nodes.
package dummy

import (
	"fmt"

	"github.com/julianshen/mmgo/pkg/layout/graph"
	"github.com/julianshen/mmgo/pkg/layout/internal/layoututil"
)

type Chain struct {
	// Dummies in rank-ascending order (from just above the edge's
	// source rank to just below its target rank).
	Dummies []string
}

type Key struct {
	From, To string
}

// Result bundles the chains inserted and every dummy ID created so
// callers can extend their own per-node maps without a second pass
// over the graph.
type Result struct {
	// Chains keyed by the rank-ascending (from, to) pair. Per-key
	// slices order multi-edges in CompareEdgeIDs order, letting
	// callers match original edges to chains by iteration position.
	Chains map[Key][]Chain
	// Dummies is every dummy ID inserted, in the order they were
	// created. Iteration-stable for deterministic downstream state.
	Dummies []string
}

// Run inserts dummy nodes into g for every edge whose rank span
// exceeds 1.
//
// Preconditions:
//   - g is acyclic (every non-self-loop edge (u, v) has
//     ranks[u] < ranks[v]).
//   - ranks has an entry for every node in g.
//
// Side effects:
//   - Long-span edges are removed from g and replaced by chains of
//     rank-adjacent edges through new 1×1 dummy nodes.
//   - ranks gains each dummy's rank.
func Run(g *graph.Graph, ranks map[string]int) Result {
	res := Result{Chains: make(map[Key][]Chain)}

	edges := g.Edges()
	layoututil.SortEdges(edges)

	for _, eid := range edges {
		if eid.From == eid.To {
			continue
		}
		fromRank, toRank := ranks[eid.From], ranks[eid.To]
		if toRank-fromRank <= 1 {
			continue
		}

		attrs, _ := g.EdgeAttrs(eid)
		g.RemoveEdge(eid)

		dummies := make([]string, 0, toRank-fromRank-1)
		prev := eid.From
		for r := fromRank + 1; r < toRank; r++ {
			id := fmt.Sprintf("__dummy_%d_%d", eid.ID, r)
			g.SetNode(id, graph.NodeAttrs{Width: 1, Height: 1})
			ranks[id] = r
			g.SetEdge(prev, id, attrs)
			dummies = append(dummies, id)
			res.Dummies = append(res.Dummies, id)
			prev = id
		}
		g.SetEdge(prev, eid.To, attrs)

		key := Key{From: eid.From, To: eid.To}
		res.Chains[key] = append(res.Chains[key], Chain{Dummies: dummies})
	}
	return res
}

// IsDummy reports whether an id was generated by Run. The "__dummy_"
// prefix is reserved — Mermaid rejects node IDs starting with double
// underscores so collisions are impossible.
func IsDummy(id string) bool {
	return len(id) > 8 && id[:8] == "__dummy_"
}
