// Package dummy inserts "dummy" waypoint nodes into the work graph
// for every edge spanning more than one rank. The ordering and
// position phases then treat the chain of (source → dummy → dummy →
// ... → target) as a sequence of rank-adjacent edges, so long-span
// edges get intermediate coordinates to route through and no longer
// slice straight through unrelated nodes at intermediate ranks.
//
// This is the dagre-style "normalize" phase, run between rank and
// order. The original long-span edge is removed from the work graph;
// its Chain (list of dummy IDs in rank-ascending order) is returned
// so the Layout caller can reconstruct the original edge's polyline
// from the dummy positions.
package dummy

import (
	"fmt"
	"sort"

	"github.com/julianshen/mmgo/pkg/layout/graph"
)

// Chain is the list of dummy node IDs inserted between two rank-
// adjacent chains, in rank-ascending order. Empty for edges that
// span exactly one rank (no dummies needed).
type Chain struct {
	Dummies []string
}

// Key identifies a group of chains between two nodes in rank-
// ascending direction. For multiple edges between the same pair
// (multi-edges), the chains slice accumulates them in insertion
// order so the caller can match them to original edges by position.
type Key struct {
	From, To string
}

// Run inserts dummy nodes into g for every edge whose rank span
// exceeds 1 and returns a map from rank-ascending (from, to) pair
// to the ordered chains inserted between them. Chains are in the
// same order as g.Edges() saw the contributing edges.
//
// Preconditions:
//   - g is acyclic (every non-self-loop edge (u, v) must satisfy
//     ranks[u] < ranks[v]). Callers run acyclic.Run + rank.Run first.
//   - ranks contains an entry for every node in g.
//
// Side effects:
//   - Long-span edges are removed from g.
//   - Chains of rank-adjacent edges (and the dummy nodes along them)
//     are added to g; ranks is extended with each dummy's rank.
//   - Dummy nodes carry small (1×1) NodeAttrs so their layout
//     footprint is negligible; only their x-coordinate matters, as
//     a waypoint for the polyline reconstruction.
func Run(g *graph.Graph, ranks map[string]int) map[Key][]Chain {
	chains := make(map[Key][]Chain)

	// Snapshot edges before mutating. Iterate in deterministic order
	// so the dummy IDs assigned are reproducible across runs.
	edges := g.Edges()
	sort.Slice(edges, func(i, j int) bool {
		if edges[i].From != edges[j].From {
			return edges[i].From < edges[j].From
		}
		if edges[i].To != edges[j].To {
			return edges[i].To < edges[j].To
		}
		return edges[i].ID < edges[j].ID
	})

	for _, eid := range edges {
		if eid.From == eid.To {
			continue // self-loop
		}
		fromRank, toRank := ranks[eid.From], ranks[eid.To]
		span := toRank - fromRank
		if span <= 1 {
			continue // adjacent ranks, no dummies needed
		}

		attrs, _ := g.EdgeAttrs(eid)
		g.RemoveEdge(eid)

		dummies := make([]string, 0, span-1)
		prev := eid.From
		for r := fromRank + 1; r < toRank; r++ {
			id := fmt.Sprintf("__dummy_%d_%d_%d", eid.ID, fromRank, r)
			g.SetNode(id, graph.NodeAttrs{Width: 1, Height: 1})
			ranks[id] = r
			g.SetEdge(prev, id, attrs)
			dummies = append(dummies, id)
			prev = id
		}
		g.SetEdge(prev, eid.To, attrs)

		key := Key{From: eid.From, To: eid.To}
		chains[key] = append(chains[key], Chain{Dummies: dummies})
	}
	return chains
}

// IsDummy reports whether an id was generated by Run. Dummy IDs use
// a reserved "__dummy_" prefix so they cannot collide with real node
// IDs, which Mermaid rejects for containing double underscores at
// the start.
func IsDummy(id string) bool {
	return len(id) > 8 && id[:8] == "__dummy_"
}
