gitGraph TB
    commit id: "init"
    branch develop
    commit id: "wip-1"
    commit id: "wip-2"
    checkout main
    commit id: "hotfix"
    merge develop id: "merge"
    commit id: "release" tag: "v1.0"
