timeline
    title History of Computing
    section Mainframes
        1940s : ENIAC : EDVAC
        1950s : UNIVAC I : IBM 701
    section Personal Computing
        1970s : Altair 8800 : Apple I : Apple II
        1980s : IBM PC : Macintosh : Amiga
    section Web Era
        1990s : WWW : Netscape : Linux 1.0
        2000s : Wikipedia : Firefox : iPhone
